query plan{
  UACSubscription{
    nomor
    plan{
      kode
      nama
      harga{
        nominal
        currency
      }
      penetapan_harga{
        satuan
        bundle
      }
      perpanjangan
      kuota_total{
        user
        tenant
      }
      kuota_terpakai{
        user
        tenant
      }
    }
  }
}