query SalesKatalog(
		$skip: Int,
		$take: Int,
		$toko: String,
		$kostumer: String,
		$waktu: String,
		$upc: String,
		$keywords: [String]
	) {
		SalesKatalog(
			skip: $skip,
			take: $take,
			toko: $toko,
			kostumer: $kostumer,
			waktu: $waktu,
			upc: $upc,
			keywords: $keywords
		) {
			upc,
			nama,
			thumbnail,
			harga{nominal, currency},
			opsi{judul, varian{parameter, value, sku, bundle}, bundle},
			promo{judul, deskripsi, potongan{nominal, currency}},
			keywords
		}
}