#import "./../fragment/karyawan.gql"
#import "./../fragment/timezone.gql"
#import "./../fragment/money.gql"
#import "./../fragment/unit.gql"
#import "./../fragment/item.gql"
#import "./../fragment/track.gql"

query SALListOrder (
	$skip: Int,
	$take: Int,
	$tenant_id: String!,
	$nomor: String
) {
	SALListOrder (
		skip: $skip,
		take: $take,
		tenant_id: $tenant_id,
		nomor: $nomor
	) {
		nomor,
		judul,
		pemesan {
			...karyawan
		},
		penyedia {
			...karyawan
		},
		kadaluarsa {
			...timezone
		},
		total {
			...money
		},
		detail {
			upc,
			nama,
			harga {
				...money
			},
			jumlah {
				...unit
			},
			subtotal {
				...money
			},
			pengaturan {
				penetapan {
					satuan,
					bundle
				}
			},
			item {
				...item
			}
		},
		list_track {
			...track
		}
	}
}